name: goreleaser-dry-run

on:
  pull_request:
    branches:
      - main
      - release/**

permissions: read-all

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    environment: release
    defaults:
      run:
        working-directory: moca-cmd
    env:
      GOPRIVATE: github.com/mocachain
      GONOSUMDB: github.com/mocachain
      GOPROXY: https://proxy.golang.org,direct
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_SECRET }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          path: moca-cmd
      - name: Checkout moca
        uses: actions/checkout@v4
        with:
          repository: mocachain/moca
          ref: 925b543c3b63bc0ddd99b932fe6914f41b53ce7c
          path: moca
          token: ${{ secrets.GH_ACCESS_SECRET }}
      - name: Checkout moca-go-sdk
        uses: actions/checkout@v4
        with:
          repository: mocachain/moca-go-sdk
          ref: a8cbdd1da3f6fb715cd5fbf998f211ce44a784b7
          path: moca-go-sdk
          token: ${{ secrets.GH_ACCESS_SECRET }}
      - name: Checkout moca-common
        uses: actions/checkout@v4
        with:
          repository: mocachain/moca-common
          ref: 4c8a3ef119043c7bb2a3a3f55911b0993f503fe6
          path: moca-common
          token: ${{ secrets.GH_ACCESS_SECRET }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
          check-latest: true
      - name: Setup GitHub Token
        run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - name: release dry run
        run: make release-dry-run
