name: goreleaser-dry-run

on:
  pull_request:
    branches:
      - main
      - release/**

permissions: read-all

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    environment: release
    defaults:
      run:
        working-directory: moca-cmd
    env:
      GOPRIVATE: github.com/mocachain
      GONOSUMDB: github.com/mocachain
      GOPROXY: https://proxy.golang.org,direct
      GOTOOLCHAIN: local
      GO_TOOLCHAIN: local
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          path: moca-cmd
      - name: Checkout moca
        uses: actions/checkout@v4
        with:
          repository: mocachain/moca
          ref: main
          path: moca
      - name: Checkout moca-go-sdk
        uses: actions/checkout@v4
        with:
          repository: mocachain/moca-go-sdk
          ref: feat/evmos_replace
          path: moca-go-sdk
      - name: Checkout moca-common
        uses: actions/checkout@v4
        with:
          repository: mocachain/moca-common
          ref: feat/evmos_replace
          path: moca-common
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
          check-latest: true
      - name: release dry run
        run: make release-dry-run
