name: goreleaser-dry-run

on:
  pull_request:
    branches:
      - main
      - release/**

permissions: read-all

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    environment: release
    env:
      GOPRIVATE: github.com/mocachain
      GONOSUMDB: github.com/mocachain
      GOPROXY: https://proxy.golang.org,direct
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_SECRET }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
          check-latest: true
      - name: Setup GitHub Token
        run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - name: Prepare CI module replacements
        run: bash ./scripts/prepare-ci-go-mod.sh
      - name: release dry run
        run: make release-dry-run
