name: gosec

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  gosec:
    name: gosec
    strategy:
      matrix:
        go-version: [1.23.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: moca-cmd
    env:
      GOPRIVATE: github.com/mocachain
      GONOSUMDB: github.com/mocachain
      GOPROXY: https://proxy.golang.org,direct
      GOTOOLCHAIN: local
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v4
        with:
          path: moca-cmd
      - name: Checkout moca
        uses: actions/checkout@v4
        with:
          repository: mocachain/moca
          ref: main
          path: moca
      - name: Checkout moca-go-sdk
        uses: actions/checkout@v4
        with:
          repository: mocachain/moca-go-sdk
          ref: feat/evmos_replace
          path: moca-go-sdk
      - name: Checkout moca-common
        uses: actions/checkout@v4
        with:
          repository: mocachain/moca-common
          ref: feat/evmos_replace
          path: moca-common
      - uses: actions/cache@v4
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('moca-cmd/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download modules
        run: go mod download
      - name: Install gosec
        run: GOBIN=$PWD/bin go install github.com/securego/gosec/v2/cmd/gosec@v2.22.3
      - name: Run Gosec Security Scanner
        run: ./bin/gosec -quiet -confidence high -severity high ./...
